encrypt:
  salt: Qmj9YOYrRc86ub1Z

jwt:
  expiration: 5184000   #一个小时有效
  secret: 6rQhjE6d7nK27vkB5AteQ7ZWUa77E0g8HYcOe1FbL7lmDVSYdRiMM9VtriiLKig4
  issuer: com.superchakra


aliyun:
  access-key-id: 填写自己的access-key-secret
  access-key-secret: 填写自己的access-key-secret
  endpoint: 填写自己的
  bucket-name: 填写自己的
  object-name: ${spring.application.name}/


spring:
  # mysql配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL驱动
    url: jdbc:mysql://localhost:3306/media?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC  # 数据库连接URL
    username: root_media  # 数据库用户名
    password: 123456  # 数据库密码

  data:
    # Redis配置
    redis:
      host: 192.168.154.132
      port: 6379
      password: chakra
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
      timeout: 5000ms

  # file上传配置
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

# mybatis-plus配置
mybatis-plus:
  global-config:
    banner: false
    db-config:
      logic-delete-field: isDeleted # 全局逻辑删除字段名
      logic-delete-value: true # 逻辑已删除值
      logic-not-delete-value: false # 逻辑未删除值
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    auto-mapping-unknown-column-behavior: warning
    arg-name-based-constructor-auto-mapping: true
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
  type-aliases-package: com.superchakra.train.entity

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

